In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 70)
pd.set_option('display.max_columns', 50)

In [42]:
df = pd.read_csv('../data/EK_all.csv')
df = df[(df['PERFORMANCE_EVENT_CODE'] == 'A') | (df['PERFORMANCE_EVENT_CODE'] == 'M')]
df['TRUST_TRAIN_ID_AFFECTED'] = df['TRUST_TRAIN_ID_AFFECTED'].apply(lambda x: x[:-2])
df.info()

/tmp/ipykernel_29793/3857996250.py:1: DtypeWarning: Columns (17,23,28,31,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/EK_all.csv')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 546711 entries, 44738 to 790294
Data columns (total 46 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   FINANCIAL_YEAR_AND_PERIOD       546711 non-null  object
 1   ORIGIN_DEPARTURE_DATE           546711 non-null  object
 2   TRUST_TRAIN_ID_AFFECTED         546711 non-null  object
 3   PLANNED_ORIG_LOC_CODE_AFF       546711 non-null  float64
 4   PLANNED_ORIG_GBTT_DATETIME_AFF  478690 non-null  object
 5   PLANNED_ORIG_WTT_DATETIME_AFF   546711 non-null  object
 6   PLANNED_DEST_LOC_CODE_AFFECTED  546711 non-null  float64
 7   PLANNED_DEST_GBTT_DATETIME_AFF  478690 non-null  object
 8   PLANNED_DEST_WTT_DATETIME_AFF   546711 non-null  object
 9   TRAIN_SERVICE_CODE_AFFECTED     546711 non-null  int64
 10  SERVICE_GROUP_CODE_AFFECTED     546711 non-null  object
 11  OPERATOR_AFFECTED               546711 non-null  object
 12  ENGLISH_DAY_TYPE                546711 non-null  object
 13  APP_TIMETABLE_FLAG_AFF          546711 non-null  object
 14  TRAIN_SCHEDULE_TYPE_AFFECTED    546711 non-null  object
 15  TRACTION_TYPE_AFFECTED          540192 non-null  object
 16  TRAILING_LOAD_AFFECTED          0 non-null       float64
 17  TIMING_LOAD_AFFECTED            690 non-null     object
 18  UNIT_CLASS_AFFECTED             538453 non-null  float64
 19  INCIDENT_NUMBER                 546689 non-null  float64
 20  INCIDENT_CREATE_DATE            546711 non-null  object
 21  INCIDENT_START_DATETIME         546689 non-null  object
 22  INCIDENT_END_DATETIME           546689 non-null  object
 23  SECTION_CODE                    546689 non-null  object
 24  NETWORK_RAIL_LOCATION_MANAGER   546689 non-null  object
 25  RESPONSIBLE_MANAGER             546689 non-null  object
 26  INCIDENT_REASON                 546662 non-null  object
 27  ATTRIBUTION_STATUS              546689 non-null  object
 28  INCIDENT_EQUIPMENT              266888 non-null  object
 29  INCIDENT_DESCRIPTION            546689 non-null  object
 30  REACTIONARY_REASON_CODE         310390 non-null  object
 31  INCIDENT_RESPONSIBLE_TRAIN      304477 non-null  object
 32  PERFORMANCE_EVENT_CODE          546711 non-null  object
 33  START_STANOX                    546711 non-null  float64
 34  END_STANOX                      546711 non-null  float64
 35  EVENT_DATETIME                  546711 non-null  object
 36  PFPI_MINUTES                    546689 non-null  float64
 37  RESP_TRAIN                      284085 non-null  object
 38  REACT_TRAIN                     305776 non-null  object
 39  Lat_OR                          546711 non-null  float64
 40  Lon_OR                          546711 non-null  float64
 41  STATION_OR                      459174 non-null  object
 42  Lat_DES                         546711 non-null  float64
 43  Lon_DES                         546711 non-null  float64
 44  STATION_DES                     417203 non-null  object
 45  INCIDENT_REASON_DESCRIPTION     546711 non-null  object
dtypes: float64(12), int64(1), object(33)
memory usage: 196.0+ MB

In [43]:
df.tail()

,FINANCIAL_YEAR_AND_PERIOD,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_ORIG_GBTT_DATETIME_AFF,PLANNED_ORIG_WTT_DATETIME_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,PLANNED_DEST_GBTT_DATETIME_AFF,PLANNED_DEST_WTT_DATETIME_AFF,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,OPERATOR_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,TRAILING_LOAD_AFFECTED,TIMING_LOAD_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_NUMBER,INCIDENT_CREATE_DATE,INCIDENT_START_DATETIME,INCIDENT_END_DATETIME,SECTION_CODE,NETWORK_RAIL_LOCATION_MANAGER,RESPONSIBLE_MANAGER,INCIDENT_REASON,ATTRIBUTION_STATUS,INCIDENT_EQUIPMENT,INCIDENT_DESCRIPTION,REACTIONARY_REASON_CODE,INCIDENT_RESPONSIBLE_TRAIN,PERFORMANCE_EVENT_CODE,START_STANOX,END_STANOX,EVENT_DATETIME,PFPI_MINUTES,RESP_TRAIN,REACT_TRAIN,Lat_OR,Lon_OR,STATION_OR,Lat_DES,Lon_DES,STATION_DES,INCIDENT_REASON_DESCRIPTION
790289,2022/23_P11,2023-01-14,879D60MZ,87651.0,2023-01-14 20:16:00,2023-01-14 20:16:00,52051.0,2023-01-14 21:08:00,2023-01-14 21:06:00,22215003,EK03,EK,SA,Y,LTP,EMU,NaN,NaN,378.0,203759.0,2023-01-14,2023-01-14 20:00:00,2023-01-15 04:25:00,63633,OQM6,OQBN,OF,Attribution Agreed,NaN,9T52 ETCS ZFD,YO,NaN,M,87651.0,87643.0,2023-01-14 20:28:00,7.0,NaN,871L59MY14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Delay due to incorrect ETCS system or equipmen...
790291,2022/23_P11,2023-01-14,879D61MZ,87651.0,2023-01-14 20:31:00,2023-01-14 20:31:00,52051.0,2023-01-14 21:23:00,2023-01-14 21:21:00,22215003,EK03,EK,SA,Y,LTP,EMU,NaN,NaN,378.0,203759.0,2023-01-14,2023-01-14 20:00:00,2023-01-15 04:25:00,63633,OQM6,OQBN,OF,Attribution Agreed,NaN,9T52 ETCS ZFD,YD,NaN,M,87651.0,87643.0,2023-01-14 20:41:00,5.0,NaN,872K611Z14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Delay due to incorrect ETCS system or equipmen...
790292,2022/23_P12,2023-02-14,872L39MP,87219.0,2023-02-14 14:46:00,2023-02-14 14:46:00,52226.0,2023-02-14 15:50:00,2023-02-14 15:50:00,22204000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YB,2U14,M,87205.0,72241.0,2023-02-14 14:59:00,3.0,NaN,896V18CI14,51.471070,-0.16936,LATCHMERE JN,51.497930,-0.210160,KENSINGTON (OLYMPIA),Confirmed shoe beam or associated system fault...
790293,2022/23_P12,2023-02-14,872N40MP,87132.0,2023-02-14 14:56:00,2023-02-14 14:56:00,52226.0,2023-02-14 15:58:00,2023-02-14 15:56:00,22214000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YD,2U14,M,72275.0,72419.0,2023-02-14 15:33:00,3.0,NaN,872L39MP14,51.532500,-0.24454,NaN,51.555480,-0.151360,GOSPEL OAK,Confirmed shoe beam or associated system fault...
790294,2022/23_P12,2023-02-14,879D35MO,87651.0,2023-02-14 14:01:00,2023-02-14 14:01:00,52051.0,2023-02-14 14:53:00,2023-02-14 14:51:00,22215003,EK03,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YD,2U14,M,87651.0,87643.0,2023-02-14 14:09:00,1.0,NaN,872K35MN14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Confirmed shoe beam or associated system fault...

In [70]:
df.ATTRIBUTION_STATUS.value_counts()

Attribution Agreed      479349
Attribution Disputed     65859
Waiting Acceptance        1481
Name: ATTRIBUTION_STATUS, dtype: int64

In [65]:
df[df['TRUST_TRAIN_ID_AFFECTED'] == '720Z021I']

,FINANCIAL_YEAR_AND_PERIOD,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_ORIG_GBTT_DATETIME_AFF,PLANNED_ORIG_WTT_DATETIME_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,PLANNED_DEST_GBTT_DATETIME_AFF,PLANNED_DEST_WTT_DATETIME_AFF,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,OPERATOR_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,TRAILING_LOAD_AFFECTED,TIMING_LOAD_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_NUMBER,INCIDENT_CREATE_DATE,INCIDENT_START_DATETIME,INCIDENT_END_DATETIME,SECTION_CODE,NETWORK_RAIL_LOCATION_MANAGER,RESPONSIBLE_MANAGER,INCIDENT_REASON,ATTRIBUTION_STATUS,INCIDENT_EQUIPMENT,INCIDENT_DESCRIPTION,REACTIONARY_REASON_CODE,INCIDENT_RESPONSIBLE_TRAIN,PERFORMANCE_EVENT_CODE,START_STANOX,END_STANOX,EVENT_DATETIME,PFPI_MINUTES,RESP_TRAIN,REACT_TRAIN,Lat_OR,Lon_OR,STATION_OR,Lat_DES,Lon_DES,STATION_DES,INCIDENT_REASON_DESCRIPTION
278882,2019/20_P01,2019-04-25,720Z021I,72277.0,NaN,2019-04-25 11:16:00,72271.0,NaN,2019-04-25 14:05:00,21921000,EK01,EK,WD,Y,(V)STP Base,D,NaN,NaN,NaN,950517.0,2019-04-25,2019-04-25 11:16:00,2019-04-25 13:16:00,72419:72277,OQRU,QQAK,QM,Attribution Agreed,711513,3Z02 SCHEDULE WJL,NaN,513Z021E25,M,72277.0,72277.0,2019-04-25 11:21:00,0.0,513Z021E25,NaN,51.5324,-0.24453,WILLESDEN JN LOW LEVEL,51.5324,-0.24453,WILLESDEN JN LOW LEVEL,Train schedule/STP Process including erroneous...

In [75]:
df[df.INCIDENT_REASON.isnull()]

,FINANCIAL_YEAR_AND_PERIOD,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_ORIG_GBTT_DATETIME_AFF,PLANNED_ORIG_WTT_DATETIME_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,PLANNED_DEST_GBTT_DATETIME_AFF,PLANNED_DEST_WTT_DATETIME_AFF,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,OPERATOR_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,TRAILING_LOAD_AFFECTED,TIMING_LOAD_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_NUMBER,INCIDENT_CREATE_DATE,INCIDENT_START_DATETIME,INCIDENT_END_DATETIME,SECTION_CODE,NETWORK_RAIL_LOCATION_MANAGER,RESPONSIBLE_MANAGER,INCIDENT_REASON,ATTRIBUTION_STATUS,INCIDENT_EQUIPMENT,INCIDENT_DESCRIPTION,REACTIONARY_REASON_CODE,INCIDENT_RESPONSIBLE_TRAIN,PERFORMANCE_EVENT_CODE,START_STANOX,END_STANOX,EVENT_DATETIME,PFPI_MINUTES,RESP_TRAIN,REACT_TRAIN,Lat_OR,Lon_OR,STATION_OR,Lat_DES,Lon_DES,STATION_DES,INCIDENT_REASON_DESCRIPTION
560869,2018/19_P01,2018-04-03,722Y34M9,72275.0,2018-04-03 23:16:00,2018-04-03 23:16:00,87219.0,2018-04-03 23:41:00,2018-04-03 23:41:00,22204000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,375.0,930464.0,2018-04-03,2018-04-03 18:00:00,2018-04-04 03:15:00,07966:07975,OQL8,MHF1,NaN,Attribution Agreed,390138,1M18 LOSS OF POWER SYMNGTN,YB,1M18,M,72275.0,72237.0,2018-04-03 23:24:00,2.0,071M18MV03,702O79M803,51.532500,-0.244540,NaN,51.526520,-0.235690,MITRE BRIDGE JN,On train TASS/TILT failure
560870,2018/19_P03,2018-06-05,522Y10MA,52226.0,2018-06-05 07:05:00,2018-06-05 07:05:00,87219.0,2018-06-05 08:07:00,2018-06-05 08:07:00,22204000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,375.0,84961.0,2018-06-04,2018-06-04 20:00:00,2018-06-04 22:10:00,43031:32571,OQRQ,MHF8,NaN,Attribution Agreed,390011,1H07 NON TILT EUS MAN,YD,721H07MZ04,M,72241.0,72241.0,2018-06-05 07:59:00,2.0,721H07MZ04,712O15MA05,51.497930,-0.210160,KENSINGTON (OLYMPIA),51.497930,-0.210160,KENSINGTON (OLYMPIA),On train TASS/TILT failure
560871,2018/19_P04,2018-06-25,722D51M7,72410.0,2018-06-25 21:37:00,2018-06-25 21:37:00,72000.0,2018-06-25 22:24:00,2018-06-25 22:24:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,139794.0,2018-06-25,2018-06-25 14:47:00,2018-06-26 14:47:00,70030:70050,OQRA,MHF1,NaN,Attribution Agreed,390135,390135 NON TILT MAN EUS,YB,321A37MM25,M,72410.0,72410.0,2018-06-25 21:41:00,4.0,321A37MM25,321A66MX25,51.529910,-0.135920,LONDON EUSTON,51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
560872,2018/19_P04,2018-07-03,722D89MD,72410.0,2018-07-03 08:57:00,2018-07-03 08:57:00,72000.0,2018-07-03 09:48:00,2018-07-03 09:44:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,161725.0,2018-07-03,2018-07-03 07:40:00,2018-07-03 09:40:00,70050:70201,OQRA,MHF1,NaN,Attribution Agreed,390154,1R11 NON TILT 390154 XWZ XHN,YB,361R11M603,M,72410.0,72410.0,2018-07-03 09:01:00,4.0,361R11M603,722N07MD03,51.529910,-0.135920,LONDON EUSTON,51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
560873,2018/19_P09,2018-11-27,722C19MI,72000.0,2018-11-27 11:01:00,2018-11-27 11:01:00,72410.0,2018-11-27 11:54:00,2018-11-27 11:49:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,579260.0,2018-11-27,2018-11-27 09:14:00,2018-11-27 17:14:00,09161:09312,OQRO,MHF1,NaN,Attribution Agreed,390107,1M07 NON TILT GLC EUS,YB,071M07M627,M,72311.0,72410.0,2018-11-27 11:52:00,3.0,071M07M627,729S65MJ27,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
560874,2019/20_P04,2019-06-29,722D67MN,72410.0,2019-06-29 13:57:00,2019-06-29 13:57:00,72000.0,2019-06-29 14:51:00,2019-06-29 14:46:00,22216000,EK02,EK,SA,Y,(V)STP Overlay,EMU,NaN,NaN,313.0,112203.0,2019-06-29,2019-06-29 13:48:00,2019-06-29 15:47:00,72410:72268,OQRE,MHF7,NaN,Attribution Agreed,221105,9S77 BRAKE APP EUS XWI,YD,729S77MN29,M,72410.0,72410.0,2019-06-29 14:04:00,7.0,729S77MN29,721F18MO29,51.529910,-0.135920,LONDON EUSTON,51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
560888,2019/20_P06,2019-08-21,722D43MY,72410.0,2019-08-21 19:44:00,2019-08-21 19:44:00,72000.0,2019-08-21 20:36:00,2019-08-21 20:34:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72017.0,2019-08-21 20:23:00,NaN,NaN,722J32MY21,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560889,2019/20_P06,2019-08-21,722D43MY,72410.0,2019-08-21 19:44:00,2019-08-21 19:44:00,72000.0,2019-08-21 20:36:00,2019-08-21 20:34:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72311.0,72277.0,2019-08-21 20:05:00,NaN,NaN,722J32MY21,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.532400,-0.244530,WILLESDEN JN LOW LEVEL,On train TASS/TILT failure
560890,2019/20_P06,2019-08-22,722C59MZ,72000.0,2019-08-22 20:01:00,2019-08-22 20:01:00,72410.0,2019-08-22 20:52:00,2019-08-22 20:50:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72017.0,72277.0,2019-08-22 20:36:00,NaN,NaN,722A03MZ22,51.592178,-0.334548,Harrow & Wealdstone Rail Station,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,On train TASS/TILT failure
560891,2019/20_P06,2019-08-22,722D38MZ,72410.0,2019-08-22 20:57:00,2019-08-22 20:57:00,72000.0,2019-08-22 21:49:00,2019-08-22 21:46:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72017.0,2019-08-22 21:31:00,NaN,NaN,722J41MZ22,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560892,2019/20_P06,2019-08-22,722D45MY,72410.0,2019-08-22 19:14:00,2019-08-22 19:14:00,72000.0,2019-08-22 20:06:00,2019-08-22 20:04:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72311.0,72311.0,2019-08-22 19:26:00,NaN,NaN,722I23MX22,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.534000,-0.205620,QUEEN'S PARK (LONDON),On train TASS/TILT failure
560893,2019/20_P06,2019-08-22,722D53MU,72410.0,2019-08-22 17:14:00,2019-08-22 17:14:00,72000.0,2019-08-22 18:06:00,2019-08-22 18:04:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72017.0,2019-08-22 17:53:00,NaN,NaN,722J23MT22,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560895,2019/20_P06,2019-08-26,722C221I,72000.0,2019-08-26 11:18:00,2019-08-26 11:18:00,72277.0,2019-08-26 11:50:00,2019-08-26 11:50:00,22216000,EK02,EK,BH,Y,(V)STP Base,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YO,NaN,M,72017.0,72277.0,2019-08-26 11:53:00,NaN,NaN,722A07ML26,51.592178,-0.334548,Harrow & Wealdstone Rail Station,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,On train TASS/TILT failure
560896,2019/20_P06,2019-08-27,722D31M8,72410.0,2019-08-27 22:45:00,2019-08-27 22:45:00,72000.0,2019-08-27 23:33:00,2019-08-27 23:33:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72017.0,2019-08-27 23:20:00,NaN,NaN,722J26M827,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560897,2019/20_P06,2019-08-27,722D31M8,72410.0,2019-08-27 22:45:00,2019-08-27 22:45:00,72000.0,2019-08-27 23:33:00,2019-08-27 23:33:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72311.0,72311.0,2019-08-27 22:56:00,NaN,NaN,722J26M827,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.534000,-0.205620,QUEEN'S PARK (LONDON),On train TASS/TILT failure
560898,2019/20_P06,2019-08-27,722D33M8,72410.0,2019-08-27 22:15:00,2019-08-27 22:15:00,72000.0,2019-08-27 23:03:00,2019-08-27 23:03:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72017.0,2019-08-27 22:49:00,NaN,NaN,722J05M727,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560900,2019/20_P06,2019-08-27,722D33M8,72410.0,2019-08-27 22:15:00,2019-08-27 22:15:00,72000.0,2019-08-27 23:03:00,2019-08-27 23:03:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72311.0,72311.0,2019-08-27 22:26:00,NaN,NaN,722J05M727,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.534000,-0.205620,QUEEN'S PARK (LONDON),On train TASS/TILT failure
560901,2019/20_P06,2019-08-27,722D33M8,72410.0,2019-08-27 22:15:00,2019-08-27 22:15:00,72000.0,2019-08-27 23:03:00,2019-08-27 23:03:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72311.0,72277.0,2019-08-27 22:31:00,NaN,NaN,722J05M727,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.532400,-0.244530,WILLESDEN JN LOW LEVEL,On train TASS/TILT failure
560902,2019/20_P06,2019-08-28,722C63M7,72000.0,2019-08-28 21:01:00,2019-08-28 21:01:00,72410.0,2019-08-28 21:52:00,2019-08-28 21:50:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72017.0,72277.0,2019-08-28 21:37:00,NaN,NaN,722A42M728,51.592178,-0.334548,Harrow & Wealdstone Rail Station,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,On train TASS/TILT failure
560903,2019/20_P06,2019-08-28,722D29M9,72410.0,2019-08-28 23:15:00,2019-08-28 23:15:00,72000.0,2019-08-29 00:03:00,2019-08-29 00:03:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72277.0,2019-08-28 23:31:00,NaN,NaN,722J31N828,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,On train TASS/TILT failure
560904,2019/20_P06,2019-08-28,722D37M7,72410.0,2019-08-28 21:15:00,2019-08-28 21:15:00,72000.0,2019-08-28 22:03:00,2019-08-28 22:03:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YI,NaN,M,72410.0,72410.0,2019-08-28 21:17:00,NaN,NaN,722C60MZ28,51.529910,-0.135920,LONDON EUSTON,51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
560905,2019/20_P06,2019-08-28,722C63M7,72000.0,2019-08-28 21:01:00,2019-08-28 21:01:00,72410.0,2019-08-28 21:52:00,2019-08-28 21:50:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72017.0,72017.0,2019-08-28 21:19:00,NaN,NaN,722A42M728,51.592178,-0.334548,Harrow & Wealdstone Rail Station,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560906,2019/20_P06,2019-08-31,722D57MS,72410.0,2019-08-31 16:28:00,2019-08-31 16:28:00,72000.0,2019-08-31 17:16:00,2019-08-31 17:16:00,22216000,EK02,EK,SA,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72017.0,2019-08-31 17:01:00,NaN,NaN,NaN,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560912,2019/20_P07,2019-09-18,722D99M5,72410.0,2019-09-18 05:37:00,2019-09-18 05:37:00,72000.0,2019-09-18 06:25:00,2019-09-18 06:25:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YX,NaN,M,72277.0,72017.0,2019-09-18 06:10:00,NaN,NaN,722J25M518,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560915,2019/20_P07,2019-09-24,722D94M6,72410.0,2019-09-24 06:58:00,2019-09-24 06:58:00,72000.0,2019-09-24 07:46:00,2019-09-24 07:46:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72277.0,72017.0,2019-09-24 07:31:00,NaN,NaN,722J36M624,51.532400,-0.244530,WILLESDEN JN LOW LEVEL,51.592178,-0.334548,Harrow & Wealdstone Rail Station,On train TASS/TILT failure
560916,2019/20_P07,2019-09-24,872L27MD,87219.0,2019-09-24 08:36:00,2019-09-24 08:36:00,52226.0,2019-09-24 09:41:00,2019-09-24 09:39:00,22204000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,375.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TO,NaN,M,72237.0,72275.0,2019-09-24 08:59:00,NaN,NaN,NaN,51.526520,-0.235690,MITRE BRIDGE JN,51.532500,-0.244540,NaN,On train TASS/TILT failure
560920,2019/20_P07,2019-09-29,722D57MW,72410.0,2019-09-29 18:15:00,2019-09-29 18:15:00,72000.0,2019-09-29 19:03:00,2019-09-29 19:03:00,22216000,EK02,EK,SU,Y,LTP,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YD,NaN,M,72410.0,72410.0,2019-09-29 18:17:00,NaN,NaN,651W74MS29,51.529910,-0.135920,LONDON EUSTON,51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
560977,2019/20_P11,2020-01-22,722D52MU,72410.0,2020-01-22 17:27:00,2020-01-22 17:27:00,72000.0,2020-01-22 18:19:00,2020-01-22 18:16:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,713484.0,2020-01-22,2020-01-22 11:41:00,2020-01-22 20:28:00,07966:07975,OQL8,MHF8,NaN,Attribution Agreed,390009,9M54 3 LOST CRSTRSS BEATCKS,YB,9M54,M,72410.0,72410.0,2020-01-22 17:29:00,1.0,049M54MH22,725T51MU22,51.529910,-0.135920,LONDON EUSTON,51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
560998,2019/20_P12,2020-02-04,725Z041J,72412.0,NaN,2020-04-02 11:56:00,72289.0,NaN,2020-04-02 12:19:00,22216001,EK99,EK,WD,Y,(V)STP Base,EMU,NaN,NaN,313.0,NaN,1994-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YI,NaN,M,72412.0,72412.0,2020-04-02 12:03:00,NaN,NaN,NaN,51.530140,-0.230600,KENSAL GREEN TURNBACK,51.530140,-0.230600,KENSAL GREEN TURNBACK,On train TASS/TILT failure
561013,2019/20_P12,2020-02-19,722C15MD,72000.0,2020-02-19 08:59:00,2020-02-19 08:59:00,72410.0,2020-02-19 09:52:00,2020-02-19 09:51:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,313.0,792866.0,2020-02-19,2020-02-19 07:15:00,2020-02-19 15:16:00,32563:32568,OQFQ,MHF1,NaN,Attribution Agreed,390118,1R17 UNIT PROBLEMS CHU WML,YD,321R17M619,M,72311.0,72410.0,2020-02-19 09:54:00,3.0,321R17M619,702T12ME19,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
561250,2020/21_P13,2021-03-15,522N70M9,52226.0,2021-03-15 23:44:00,2021-03-15 23:44:00,72275.0,2021-03-16 00:26:00,2021-03-16 00:23:00,22214000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YD,721H73MX15,M,52054.0,72421.0,2021-03-16 00:09:00,6.0,721H73MX15,525M49M915,51.547260,-0.098800,CANONBURY WEST JN,51.541890,-0.139280,CAMDEN ROAD JN,On train TASS/TILT failure
561251,2020/21_P13,2021-03-15,525M45M9,52226.0,NaN,2021-03-15 23:03:00,72410.0,NaN,2021-03-16 00:15:00,22216001,EK99,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YG,721H73MX15,M,72421.0,72311.0,2021-03-16 00:12:00,6.0,721H73MX15,729G49M915,51.541890,-0.139280,CAMDEN ROAD JN,51.534000,-0.205620,QUEEN'S PARK (LONDON),On train TASS/TILT failure
561252,2020/21_P13,2021-03-15,525M49M9,52226.0,NaN,2021-03-15 23:35:00,72271.0,NaN,2021-03-16 00:30:00,22216001,EK99,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YD,721H73MX15,M,52054.0,72421.0,2021-03-16 00:07:00,6.0,721H73MX15,525M45M915,51.547260,-0.098800,CANONBURY WEST JN,51.541890,-0.139280,CAMDEN ROAD JN,On train TASS/TILT failure
561253,2020/21_P13,2021-03-15,525M51M9,52226.0,NaN,2021-03-15 23:51:00,72116.0,NaN,2021-03-16 00:49:00,22216001,EK99,EK,WD,Y,(V)STP Overlay,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YG,721H73MX15,M,72421.0,72268.0,2021-03-16 00:25:00,4.0,721H73MX15,725M19M016,51.541890,-0.139280,CAMDEN ROAD JN,51.530940,-0.241300,WILLESDEN WEST LONDN JN,On train TASS/TILT failure
561254,2020/21_P13,2021-03-15,529G74M9,52074.0,2021-03-15 23:50:00,2021-03-15 23:50:00,87219.0,2021-03-16 00:35:00,2021-03-16 00:35:00,22206000,EK03,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YB,721H73MX15,M,87208.0,87219.0,2021-03-16 00:39:00,4.0,721H73MX15,875M68M016,51.467260,-0.135220,VOLTAIRE ROAD JN.,51.463350,-0.172530,CLAPHAM JUNCTION,On train TASS/TILT failure
561255,2020/21_P13,2021-03-15,722C72M9,72000.0,2021-03-15 23:18:00,2021-03-15 23:18:00,72410.0,2021-03-16 00:09:00,2021-03-16 00:08:00,22216000,EK02,EK,WD,Y,LTP,EMU,NaN,NaN,710.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YG,721H73MX15,M,72311.0,72410.0,2021-03-16 00:11:00,3.0,721H73MX15,651B45M715,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
561256,2020/21_P13,2021-03-16,722Y68M0,72275.0,2021-03-16 00:05:00,2021-03-16 00:05:00,87219.0,2021-03-16 00:25:00,2021-03-16 00:24:00,22204000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YB,721H73MX15,M,72275.0,72237.0,2021-03-16 00:12:00,5.0,721H73MX15,712O811915,51.532500,-0.244540,NaN,51.526520,-0.235690,MITRE BRIDGE JN,On train TASS/TILT failure
561257,2020/21_P13,2021-03-16,873G74M0,87219.0,NaN,2021-03-16 00:37:00,87227.0,NaN,2021-03-16 00:38:00,22216001,EK99,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YI,721H73MX15,M,87219.0,87219.0,2021-03-16 00:41:00,4.0,721H73MX15,529G74M915,51.463350,-0.172530,CLAPHAM JUNCTION,51.463350,-0.172530,CLAPHAM JUNCTION,On train TASS/TILT failure
561258,2020/21_P13,2021-03-16,875M68M0,87219.0,NaN,2021-03-16 00:29:00,72116.0,NaN,2021-03-16 00:52:00,22216001,EK99,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YC,721H73MX15,M,72268.0,72116.0,2021-03-16 01:05:00,5.0,721H73MX15,725M70M016,51.530940,-0.241300,WILLESDEN WEST LONDN JN,51.542210,-0.276550,NaN,On train TASS/TILT failure
561259,2020/21_P13,2021-03-16,875M68M0,87219.0,NaN,2021-03-16 00:29:00,72116.0,NaN,2021-03-16 00:52:00,22216001,EK99,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,563914.0,2021-03-15,2021-03-15 20:10:00,2021-03-15 22:10:00,43314:42302,OQNS,MHF1,NaN,Attribution Agreed,390130,1H73 UNIT FAULT NTNB,YI,721H73MX15,M,87219.0,87219.0,2021-03-16 00:36:00,7.0,721H73MX15,722Y68M016,51.463350,-0.172530,CLAPHAM JUNCTION,51.463350,-0.172530,CLAPHAM JUNCTION,On train TASS/TILT failure
561260,2021/22_P06,2021-08-28,722C14MD,72000.0,2021-08-28 08:45:00,2021-08-28 08:45:00,72410.0,2021-08-28 09:36:00,2021-08-28 09:36:00,22216000,EK02,EK,SA,Y,LTP,EMU,NaN,NaN,378.0,919109.0,2021-08-28,2021-08-28 08:38:00,2021-08-28 08:38:00,69021:70030,OQNA,DHFA,NaN,Attribution Agreed,390119,1A09 NON TILT NUN RUG,YD,321A09MA28,M,72311.0,72410.0,2021-08-28 09:44:00,4.0,321A09MA28,321A09MA28,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure
561261,2021/22_P06,2021-08-28,722C15ME,72000.0,2021-08-28 09:00:00,2021-08-28 09:00:00,72410.0,2021-08-28 09:50:00,2021-08-28 09:50:00,22216000,EK02,EK,SA,Y,LTP,EMU,NaN,NaN,710.0,919109.0,2021-08-28,2021-08-28 08:38:00,2021-08-28 08:38:00,69021:70030,OQNA,DHFA,NaN,Attribution Agreed,390119,1A09 NON TILT NUN RUG,YD,321A09MA28,M,72311.0,72410.0,2021-08-28 09:57:00,3.5,321A09MA28,659A46MB28,51.534000,-0.205620,QUEEN'S PARK (LONDON),51.529910,-0.135920,LONDON EUSTON,On train TASS/TILT failure

In [76]:
reasons_csv = pd.read_excel('https://sacuksprodnrdigital0001.blob.core.windows.net/historic-delay-attribution/Reference%20Files/Transpareny%20Page%20Attribution%20Glossary.xlsx', sheet_name='Incident Reason')[['Incident Reason', 'Incident Reason Description']]
reasons_csv.rename(columns={'Incident Reason': 'INCIDENT_REASON', 'Incident Reason Description': 'INCIDENT_REASON_DESCRIPTION'}, inplace=True)
reasons_csv

    INCIDENT_REASON                        INCIDENT_REASON_DESCRIPTION
0                IB          Points failure (including no fault found)
1                IP  Points failure caused by snow or frost where h...
2                JT  Points failure caused by snow or frost where h...
3                IQ  Trackside sign blown down, fallen over, missin...
4                ID  Level crossing faults and failure incl. barrow...
..              ...                                                ...
361              YO  Waiting platform/station congestion/platform c...
362              YQ  Passenger overcrowding caused by a train being...
363              YR  Tactical cancellation for service recovery not...
364              YU  Service Recovery-booked rolling stock, not ava...
365              YX  Passenger overcrowding caused by delay or canc...

[366 rows x 2 columns]

In [86]:
def fill_incident(incident, react):
    if pd.isnull(incident):
        return react
    return incident
    
df['INCIDENT_REASON'] = df.apply(lambda x: fill_incident(x['INCIDENT_REASON'], x['REACTIONARY_REASON_CODE']), axis=1)
df

,FINANCIAL_YEAR_AND_PERIOD,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_ORIG_GBTT_DATETIME_AFF,PLANNED_ORIG_WTT_DATETIME_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,PLANNED_DEST_GBTT_DATETIME_AFF,PLANNED_DEST_WTT_DATETIME_AFF,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,OPERATOR_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,TRAILING_LOAD_AFFECTED,TIMING_LOAD_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_NUMBER,INCIDENT_CREATE_DATE,INCIDENT_START_DATETIME,INCIDENT_END_DATETIME,SECTION_CODE,NETWORK_RAIL_LOCATION_MANAGER,RESPONSIBLE_MANAGER,INCIDENT_REASON,ATTRIBUTION_STATUS,INCIDENT_EQUIPMENT,INCIDENT_DESCRIPTION,REACTIONARY_REASON_CODE,INCIDENT_RESPONSIBLE_TRAIN,PERFORMANCE_EVENT_CODE,START_STANOX,END_STANOX,EVENT_DATETIME,PFPI_MINUTES,RESP_TRAIN,REACT_TRAIN,Lat_OR,Lon_OR,STATION_OR,Lat_DES,Lon_DES,STATION_DES,INCIDENT_REASON_DESCRIPTION
44738,2018/19_P01,2018-04-01,512J19MI,51531.0,2018-04-01 11:08:00,2018-04-01 11:08:00,72419.0,2018-04-01 11:45:00,2018-04-01 11:43:00,21921000,EK01,EK,SU,Y,LTP,DMS,NaN,S,NaN,925750.0,2018-04-01,2018-04-01 11:32:00,2018-04-01 19:50:00,72419:51558,OQHS,MEKF,MD,Attribution Agreed,172002,2J22 POWER DEFECT UHL,YO,2J22,M,51558.0,72419.0,2018-04-01 11:49:00,6.0,722J22MI01,722J24MJ01,51.580430,-0.07182,SOUTH TOTTENHAM,51.555480,-0.151360,GOSPEL OAK,Technical failures below the solebar
44745,2018/19_P01,2018-04-01,722J22MI,72419.0,2018-04-01 11:25:00,2018-04-01 11:25:00,51531.0,2018-04-01 12:01:00,2018-04-01 11:59:00,21921000,EK01,EK,SU,Y,LTP,DMS,NaN,S,NaN,925750.0,2018-04-01,2018-04-01 11:32:00,2018-04-01 19:50:00,72419:51558,OQHS,MEKF,MD,Attribution Agreed,172002,2J22 POWER DEFECT UHL,NaN,2J22,M,72419.0,51558.0,2018-04-01 11:50:00,13.0,722J22MI01,NaN,51.555480,-0.15136,GOSPEL OAK,51.580430,-0.071820,SOUTH TOTTENHAM,Technical failures below the solebar
44746,2018/19_P01,2018-04-01,722J24MJ,72419.0,2018-04-01 11:40:00,2018-04-01 11:40:00,51531.0,2018-04-01 12:16:00,2018-04-01 12:14:00,21921000,EK01,EK,SU,Y,LTP,DMS,NaN,S,NaN,925750.0,2018-04-01,2018-04-01 11:32:00,2018-04-01 19:50:00,72419:51558,OQHS,MEKF,MD,Attribution Agreed,172002,2J22 POWER DEFECT UHL,YB,2J22,M,72419.0,72419.0,2018-04-01 11:46:00,6.0,722J22MI01,722J22MI01,51.555480,-0.15136,GOSPEL OAK,51.555480,-0.151360,GOSPEL OAK,Technical failures below the solebar
44748,2018/19_P01,2018-04-02,529C7118,52051.0,2018-04-02 22:57:00,2018-04-02 22:57:00,87651.0,2018-04-02 23:52:00,2018-04-02 23:47:00,22215003,EK03,EK,BH,Y,(V)STP Base,EMU,NaN,NaN,375.0,928370.0,2018-04-02,2018-04-02 22:54:00,2018-04-03 06:56:00,52074:52051,OQYA,MEKI,MD,Attribution Agreed,378148,9D66 UNIT DEFECT CNN,YI,9D66,M,52051.0,52051.0,2018-04-02 23:06:00,9.0,879D661702,879B671802,51.180550,0.49318,HIGHBURY AND ISLINGTON ELL,51.180550,0.493180,HIGHBURY AND ISLINGTON ELL,Technical failures below the solebar
44750,2018/19_P01,2018-04-02,529C461T,52051.0,2018-04-02 16:42:00,2018-04-02 16:42:00,87651.0,2018-04-02 17:37:00,2018-04-02 17:32:00,22215003,EK03,EK,BH,Y,(V)STP Base,EMU,NaN,NaN,375.0,927762.0,2018-04-02,2018-04-02 16:24:00,2018-04-03 00:45:00,88392:87568,OQYA,MEKA,MD,Attribution Agreed,NaN,9M41 UNIT DEFECT NXG,YB,9M41,M,52051.0,52074.0,2018-04-02 16:52:00,6.0,879M411R02,879M411R02,51.180550,0.49318,HIGHBURY AND ISLINGTON ELL,51.546120,-0.075130,NaN,Technical failures below the solebar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790289,2022/23_P11,2023-01-14,879D60MZ,87651.0,2023-01-14 20:16:00,2023-01-14 20:16:00,52051.0,2023-01-14 21:08:00,2023-01-14 21:06:00,22215003,EK03,EK,SA,Y,LTP,EMU,NaN,NaN,378.0,203759.0,2023-01-14,2023-01-14 20:00:00,2023-01-15 04:25:00,63633,OQM6,OQBN,OF,Attribution Agreed,NaN,9T52 ETCS ZFD,YO,NaN,M,87651.0,87643.0,2023-01-14 20:28:00,7.0,NaN,871L59MY14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Delay due to incorrect ETCS system or equipmen...
790291,2022/23_P11,2023-01-14,879D61MZ,87651.0,2023-01-14 20:31:00,2023-01-14 20:31:00,52051.0,2023-01-14 21:23:00,2023-01-14 21:21:00,22215003,EK03,EK,SA,Y,LTP,EMU,NaN,NaN,378.0,203759.0,2023-01-14,2023-01-14 20:00:00,2023-01-15 04:25:00,63633,OQM6,OQBN,OF,Attribution Agreed,NaN,9T52 ETCS ZFD,YD,NaN,M,87651.0,87643.0,2023-01-14 20:41:00,5.0,NaN,872K611Z14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Delay due to incorrect ETCS system or equipmen...
790292,2022/23_P12,2023-02-14,872L39MP,87219.0,2023-02-14 14:46:00,2023-02-14 14:46:00,52226.0,2023-02-14 15:50:00,2023-02-14 15:50:00,22204000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YB,2U14,M,87205.0,72241.0,2023-02-14 14:59:00,3.0,NaN,896V18CI14,51.471070,-0.16936,LATCHMERE JN,51.497930,-0.210160,KENSINGTON (OLYMPIA),Confirmed shoe beam or associated system fault...
790293,2022/23_P12,2023-02-14,872N40MP,87132.0,2023-02-14 14:56:00,2023-02-14 14:56:00,52226.0,2023-02-14 15:58:00,2023-02-14 15:56:00,22214000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YD,2U14,M,72275.0,72419.0,2023-02-14 15:33:00,3.0,NaN,872L39MP14,51.532500,-0.24454,NaN,51.555480,-0.151360,GOSPEL OAK,Confirmed shoe beam or associated system fault...
790294,2022/23_P12,2023-02-14,879D35MO,87651.0,2023-02-14 14:01:00,2023-02-14 14:01:00,52051.0,2023-02-14 14:53:00,2023-02-14 14:51:00,22215003,EK03,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YD,2U14,M,87651.0,87643.0,2023-02-14 14:09:00,1.0,NaN,872K35MN14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Confirmed shoe beam or associated system fault...

In [87]:
df.drop(columns='INCIDENT_REASON_DESCRIPTION', inplace = True)

In [88]:
df = df.merge(reasons_csv, on='INCIDENT_REASON')
df

,FINANCIAL_YEAR_AND_PERIOD,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_ORIG_GBTT_DATETIME_AFF,PLANNED_ORIG_WTT_DATETIME_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,PLANNED_DEST_GBTT_DATETIME_AFF,PLANNED_DEST_WTT_DATETIME_AFF,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,OPERATOR_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,TRAILING_LOAD_AFFECTED,TIMING_LOAD_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_NUMBER,INCIDENT_CREATE_DATE,INCIDENT_START_DATETIME,INCIDENT_END_DATETIME,SECTION_CODE,NETWORK_RAIL_LOCATION_MANAGER,RESPONSIBLE_MANAGER,INCIDENT_REASON,ATTRIBUTION_STATUS,INCIDENT_EQUIPMENT,INCIDENT_DESCRIPTION,REACTIONARY_REASON_CODE,INCIDENT_RESPONSIBLE_TRAIN,PERFORMANCE_EVENT_CODE,START_STANOX,END_STANOX,EVENT_DATETIME,PFPI_MINUTES,RESP_TRAIN,REACT_TRAIN,Lat_OR,Lon_OR,STATION_OR,Lat_DES,Lon_DES,STATION_DES,INCIDENT_REASON_DESCRIPTION
0,2018/19_P01,2018-04-01,512J19MI,51531.0,2018-04-01 11:08:00,2018-04-01 11:08:00,72419.0,2018-04-01 11:45:00,2018-04-01 11:43:00,21921000,EK01,EK,SU,Y,LTP,DMS,NaN,S,NaN,925750.0,2018-04-01,2018-04-01 11:32:00,2018-04-01 19:50:00,72419:51558,OQHS,MEKF,MD,Attribution Agreed,172002,2J22 POWER DEFECT UHL,YO,2J22,M,51558.0,72419.0,2018-04-01 11:49:00,6.0,722J22MI01,722J24MJ01,51.580430,-0.07182,SOUTH TOTTENHAM,51.555480,-0.151360,GOSPEL OAK,Technical failures below the solebar
1,2018/19_P01,2018-04-01,722J22MI,72419.0,2018-04-01 11:25:00,2018-04-01 11:25:00,51531.0,2018-04-01 12:01:00,2018-04-01 11:59:00,21921000,EK01,EK,SU,Y,LTP,DMS,NaN,S,NaN,925750.0,2018-04-01,2018-04-01 11:32:00,2018-04-01 19:50:00,72419:51558,OQHS,MEKF,MD,Attribution Agreed,172002,2J22 POWER DEFECT UHL,NaN,2J22,M,72419.0,51558.0,2018-04-01 11:50:00,13.0,722J22MI01,NaN,51.555480,-0.15136,GOSPEL OAK,51.580430,-0.071820,SOUTH TOTTENHAM,Technical failures below the solebar
2,2018/19_P01,2018-04-01,722J24MJ,72419.0,2018-04-01 11:40:00,2018-04-01 11:40:00,51531.0,2018-04-01 12:16:00,2018-04-01 12:14:00,21921000,EK01,EK,SU,Y,LTP,DMS,NaN,S,NaN,925750.0,2018-04-01,2018-04-01 11:32:00,2018-04-01 19:50:00,72419:51558,OQHS,MEKF,MD,Attribution Agreed,172002,2J22 POWER DEFECT UHL,YB,2J22,M,72419.0,72419.0,2018-04-01 11:46:00,6.0,722J22MI01,722J22MI01,51.555480,-0.15136,GOSPEL OAK,51.555480,-0.151360,GOSPEL OAK,Technical failures below the solebar
3,2018/19_P01,2018-04-02,529C7118,52051.0,2018-04-02 22:57:00,2018-04-02 22:57:00,87651.0,2018-04-02 23:52:00,2018-04-02 23:47:00,22215003,EK03,EK,BH,Y,(V)STP Base,EMU,NaN,NaN,375.0,928370.0,2018-04-02,2018-04-02 22:54:00,2018-04-03 06:56:00,52074:52051,OQYA,MEKI,MD,Attribution Agreed,378148,9D66 UNIT DEFECT CNN,YI,9D66,M,52051.0,52051.0,2018-04-02 23:06:00,9.0,879D661702,879B671802,51.180550,0.49318,HIGHBURY AND ISLINGTON ELL,51.180550,0.493180,HIGHBURY AND ISLINGTON ELL,Technical failures below the solebar
4,2018/19_P01,2018-04-02,529C461T,52051.0,2018-04-02 16:42:00,2018-04-02 16:42:00,87651.0,2018-04-02 17:37:00,2018-04-02 17:32:00,22215003,EK03,EK,BH,Y,(V)STP Base,EMU,NaN,NaN,375.0,927762.0,2018-04-02,2018-04-02 16:24:00,2018-04-03 00:45:00,88392:87568,OQYA,MEKA,MD,Attribution Agreed,NaN,9M41 UNIT DEFECT NXG,YB,9M41,M,52051.0,52074.0,2018-04-02 16:52:00,6.0,879M411R02,879M411R02,51.180550,0.49318,HIGHBURY AND ISLINGTON ELL,51.546120,-0.075130,NaN,Technical failures below the solebar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546706,2022/23_P11,2023-01-14,879D60MZ,87651.0,2023-01-14 20:16:00,2023-01-14 20:16:00,52051.0,2023-01-14 21:08:00,2023-01-14 21:06:00,22215003,EK03,EK,SA,Y,LTP,EMU,NaN,NaN,378.0,203759.0,2023-01-14,2023-01-14 20:00:00,2023-01-15 04:25:00,63633,OQM6,OQBN,OF,Attribution Agreed,NaN,9T52 ETCS ZFD,YO,NaN,M,87651.0,87643.0,2023-01-14 20:28:00,7.0,NaN,871L59MY14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Delay due to incorrect ETCS system or equipmen...
546707,2022/23_P11,2023-01-14,879D61MZ,87651.0,2023-01-14 20:31:00,2023-01-14 20:31:00,52051.0,2023-01-14 21:23:00,2023-01-14 21:21:00,22215003,EK03,EK,SA,Y,LTP,EMU,NaN,NaN,378.0,203759.0,2023-01-14,2023-01-14 20:00:00,2023-01-15 04:25:00,63633,OQM6,OQBN,OF,Attribution Agreed,NaN,9T52 ETCS ZFD,YD,NaN,M,87651.0,87643.0,2023-01-14 20:41:00,5.0,NaN,872K611Z14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Delay due to incorrect ETCS system or equipmen...
546708,2022/23_P12,2023-02-14,872L39MP,87219.0,2023-02-14 14:46:00,2023-02-14 14:46:00,52226.0,2023-02-14 15:50:00,2023-02-14 15:50:00,22204000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YB,2U14,M,87205.0,72241.0,2023-02-14 14:59:00,3.0,NaN,896V18CI14,51.471070,-0.16936,LATCHMERE JN,51.497930,-0.210160,KENSINGTON (OLYMPIA),Confirmed shoe beam or associated system fault...
546709,2022/23_P12,2023-02-14,872N40MP,87132.0,2023-02-14 14:56:00,2023-02-14 14:56:00,52226.0,2023-02-14 15:58:00,2023-02-14 15:56:00,22214000,EK01,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YD,2U14,M,72275.0,72419.0,2023-02-14 15:33:00,3.0,NaN,872L39MP14,51.532500,-0.24454,NaN,51.555480,-0.151360,GOSPEL OAK,Confirmed shoe beam or associated system fault...
546710,2022/23_P12,2023-02-14,879D35MO,87651.0,2023-02-14 14:01:00,2023-02-14 14:01:00,52051.0,2023-02-14 14:53:00,2023-02-14 14:51:00,22215003,EK03,EK,WD,Y,LTP,EMU,NaN,NaN,378.0,281589.0,2023-02-14,2023-02-14 09:30:00,2023-02-14 17:51:00,88424:88466,OQM6,MHU3,MQ,Attribution Disputed,NaN,2U14 ON FIRE DFD,YD,2U14,M,87651.0,87643.0,2023-02-14 14:09:00,1.0,NaN,872K35MN14,51.378426,-0.10256,West Croydon Rail Station,51.397017,-0.075196,Norwood Junction Rail Station,Confirmed shoe beam or associated system fault...

In [98]:
df.TRAIN_SERVICE_CODE_AFFECTED.value_counts()

22214000    111696
22218000     79713
22215003     61996
21921000     55438
22216001     47959
22216000     43106
21234001     41197
22206000     30676
22204000     29123
21235001     20041
21252001     10740
25234001     10223
25235001      4597
21237001       192
22215002        14
Name: TRAIN_SERVICE_CODE_AFFECTED, dtype: int64

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 546711 entries, 0 to 546710
Data columns (total 46 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   FINANCIAL_YEAR_AND_PERIOD       546711 non-null  object
 1   ORIGIN_DEPARTURE_DATE           546711 non-null  object
 2   TRUST_TRAIN_ID_AFFECTED         546711 non-null  object
 3   PLANNED_ORIG_LOC_CODE_AFF       546711 non-null  float64
 4   PLANNED_ORIG_GBTT_DATETIME_AFF  478690 non-null  object
 5   PLANNED_ORIG_WTT_DATETIME_AFF   546711 non-null  object
 6   PLANNED_DEST_LOC_CODE_AFFECTED  546711 non-null  float64
 7   PLANNED_DEST_GBTT_DATETIME_AFF  478690 non-null  object
 8   PLANNED_DEST_WTT_DATETIME_AFF   546711 non-null  object
 9   TRAIN_SERVICE_CODE_AFFECTED     546711 non-null  int64
 10  SERVICE_GROUP_CODE_AFFECTED     546711 non-null  object
 11  OPERATOR_AFFECTED               546711 non-null  object
 12  ENGLISH_DAY_TYPE                546711 non-null  object
 13  APP_TIMETABLE_FLAG_AFF          546711 non-null  object
 14  TRAIN_SCHEDULE_TYPE_AFFECTED    546711 non-null  object
 15  TRACTION_TYPE_AFFECTED          540192 non-null  object
 16  TRAILING_LOAD_AFFECTED          0 non-null       float64
 17  TIMING_LOAD_AFFECTED            690 non-null     object
 18  UNIT_CLASS_AFFECTED             538453 non-null  float64
 19  INCIDENT_NUMBER                 546689 non-null  float64
 20  INCIDENT_CREATE_DATE            546711 non-null  object
 21  INCIDENT_START_DATETIME         546689 non-null  object
 22  INCIDENT_END_DATETIME           546689 non-null  object
 23  SECTION_CODE                    546689 non-null  object
 24  NETWORK_RAIL_LOCATION_MANAGER   546689 non-null  object
 25  RESPONSIBLE_MANAGER             546689 non-null  object
 26  INCIDENT_REASON                 546711 non-null  object
 27  ATTRIBUTION_STATUS              546689 non-null  object
 28  INCIDENT_EQUIPMENT              266888 non-null  object
 29  INCIDENT_DESCRIPTION            546689 non-null  object
 30  REACTIONARY_REASON_CODE         310390 non-null  object
 31  INCIDENT_RESPONSIBLE_TRAIN      304477 non-null  object
 32  PERFORMANCE_EVENT_CODE          546711 non-null  object
 33  START_STANOX                    546711 non-null  float64
 34  END_STANOX                      546711 non-null  float64
 35  EVENT_DATETIME                  546711 non-null  object
 36  PFPI_MINUTES                    546689 non-null  float64
 37  RESP_TRAIN                      284085 non-null  object
 38  REACT_TRAIN                     305776 non-null  object
 39  Lat_OR                          546711 non-null  float64
 40  Lon_OR                          546711 non-null  float64
 41  STATION_OR                      459174 non-null  object
 42  Lat_DES                         546711 non-null  float64
 43  Lon_DES                         546711 non-null  float64
 44  STATION_DES                     417203 non-null  object
 45  INCIDENT_REASON_DESCRIPTION     546711 non-null  object
dtypes: float64(12), int64(1), object(33)
memory usage: 212.2+ MB

In [97]:
df.TRUST_TRAIN_ID_AFFECTED.value_counts() 
# the definitive list of all delays unique train IDs - 18495 trains but could be interesting for graphs

879D11MC    1258
879D12MC    1034
873D70M9    1008
879D51MW     937
879D49MV     928
            ...
875L592L       1
725D742J       1
872N0016       1
722J9117       1
525V761Z       1
Name: TRUST_TRAIN_ID_AFFECTED, Length: 18495, dtype: int64

In [117]:
retain_columns = ['EVENT_DATETIME', 'TRAIN_SERVICE_CODE_AFFECTED', 'ENGLISH_DAY_TYPE', 'APP_TIMETABLE_FLAG_AFF', 'TRAIN_SCHEDULE_TYPE_AFFECTED', 'TRACTION_TYPE_AFFECTED','UNIT_CLASS_AFFECTED', 'INCIDENT_REASON', 'Lat_OR', 'Lon_OR', 'Lat_DES', 'Lon_DES', 'PFPI_MINUTES' ]

In [241]:
trim_df = df[retain_columns].copy()
trim_df.dropna(subset='PFPI_MINUTES', inplace=True) # drop those rows with NaN delays (why they are there in first place?!)
trim_df = trim_df[trim_df.PFPI_MINUTES != 0] # drop those with 0 minutes (same Question as above)
trim_df.loc[:, 'TRAIN_SERVICE_CODE_AFFECTED'] = trim_df.TRAIN_SERVICE_CODE_AFFECTED.astype(str) # converting to string not to confuse ourselves by scaling them accidentally
trim_df.loc[:, 'TRAIN_SCHEDULE_TYPE_AFFECTED'] = trim_df.TRAIN_SCHEDULE_TYPE_AFFECTED.apply(lambda x: 'STP' if 'STP' in x else 'LTP') # four categories here - LTP and the others (V)STP which I group them together. how they are short term planned is not our concern
trim_df = trim_df.dropna(subset= 'TRACTION_TYPE_AFFECTED') # dropping those without traction type (diesel or electronic - purely input mistake they must be either of each)
trim_df = trim_df[trim_df.TRACTION_TYPE_AFFECTED != 'L'] # wtf is L type :cry: (good there are only 3/4 rows)
trim_df.loc[:, 'UNIT_CLASS_AFFECTED'] = trim_df.UNIT_CLASS_AFFECTED.astype('Int64').astype(str) # same ideology for TSC

def is_DMS(traction_type, unit_class):
    if traction_type == 'DMS':
        return 172
    return unit_class
trim_df.loc[:, 'UNIT_CLASS_AFFECTED'] = trim_df.apply(lambda x: is_DMS(x['TRACTION_TYPE_AFFECTED'], x['UNIT_CLASS_AFFECTED']), axis=1) # mapping class 172 for Diesel locos as per described on wiki https://en.wikipedia.org/wiki/London_Overground#Past_fleet
trim_df = trim_df[trim_df.UNIT_CLASS_AFFECTED != '<NA>'] # drop those EMU locos with no specified unit class - may revisit later if domain knowledge available
trim_df.loc[:, 'INCIDENT_REASON'] = trim_df.INCIDENT_REASON.apply(lambda x: x[0]) # categorising incident code https://wiki.openraildata.com/index.php/Delay_Attribution_Guide

In [242]:
trim_df

,EVENT_DATETIME,TRAIN_SERVICE_CODE_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_REASON,Lat_OR,Lon_OR,Lat_DES,Lon_DES,PFPI_MINUTES
0,2018-04-01 11:49:00,21921000,SU,Y,LTP,DMS,172,M,51.580430,-0.07182,51.555480,-0.151360,6.0
1,2018-04-01 11:50:00,21921000,SU,Y,LTP,DMS,172,M,51.555480,-0.15136,51.580430,-0.071820,13.0
2,2018-04-01 11:46:00,21921000,SU,Y,LTP,DMS,172,M,51.555480,-0.15136,51.555480,-0.151360,6.0
3,2018-04-02 23:06:00,22215003,BH,Y,STP,EMU,375,M,51.180550,0.49318,51.180550,0.493180,9.0
4,2018-04-02 16:52:00,22215003,BH,Y,STP,EMU,375,M,51.180550,0.49318,51.546120,-0.075130,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
546706,2023-01-14 20:28:00,22215003,SA,Y,LTP,EMU,378,O,51.378426,-0.10256,51.397017,-0.075196,7.0
546707,2023-01-14 20:41:00,22215003,SA,Y,LTP,EMU,378,O,51.378426,-0.10256,51.397017,-0.075196,5.0
546708,2023-02-14 14:59:00,22204000,WD,Y,LTP,EMU,378,M,51.471070,-0.16936,51.497930,-0.210160,3.0
546709,2023-02-14 15:33:00,22214000,WD,Y,LTP,EMU,378,M,51.532500,-0.24454,51.555480,-0.151360,3.0
546710,2023-02-14 14:09:00,22215003,WD,Y,LTP,EMU,378,M,51.378426,-0.10256,51.397017,-0.075196,1.0

In [243]:
trim_df.to_csv('../data/EK_trimmed.csv', index = False)

In [125]:
# testing cyclical feature engineering for time-related columns

trim_df['MONTH_sin'] = np.sin(2*np.pi*(trim_df.EVENT_DATETIME.dt.month)/12)
trim_df['MONTH_cos'] = np.cos(2*np.pi*(trim_df.EVENT_DATETIME.dt.month)/12)
trim_df['DAY_sin'] = np.sin(2*np.pi*(trim_df.EVENT_DATETIME.dt.day)/31)
trim_df['DAY_cos'] = np.cos(2*np.pi*(trim_df.EVENT_DATETIME.dt.day)/31)
trim_df['HOUR_sin'] = np.sin(2*np.pi*(trim_df.EVENT_DATETIME.dt.hour)/24)
trim_df['HOUR_cos'] = np.cos(2*np.pi*(trim_df.EVENT_DATETIME.dt.hour)/24)
trim_df['MINUTE_sin'] = np.sin(2*np.pi*(trim_df.EVENT_DATETIME.dt.minute)/60)
trim_df['MINUTE_cos'] = np.cos(2*np.pi*(trim_df.EVENT_DATETIME.dt.minute)/60)
# all custom transformers

,EVENT_DATETIME,TRAIN_SERVICE_CODE_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_REASON,Lat_OR,Lon_OR,Lat_DES,Lon_DES,PFPI_MINUTES,MONTH_sin,MONTH_cos,DAY_sin,DAY_cos,HOUR_sin,HOUR_cos,MINUTE_sin,MINUTE_cos
0,2018-04-01 11:49:00,21921000,SU,Y,LTP,DMS,NaN,MD,51.580430,-0.07182,51.555480,-0.151360,6.0,0.866025,-0.500000,0.201299,0.979530,0.258819,-0.965926,-0.913545,0.406737
1,2018-04-01 11:50:00,21921000,SU,Y,LTP,DMS,NaN,MD,51.555480,-0.15136,51.580430,-0.071820,13.0,0.866025,-0.500000,0.201299,0.979530,0.258819,-0.965926,-0.866025,0.500000
2,2018-04-01 11:46:00,21921000,SU,Y,LTP,DMS,NaN,MD,51.555480,-0.15136,51.555480,-0.151360,6.0,0.866025,-0.500000,0.201299,0.979530,0.258819,-0.965926,-0.994522,0.104528
3,2018-04-02 23:06:00,22215003,BH,Y,(V)STP Base,EMU,375.0,MD,51.180550,0.49318,51.180550,0.493180,9.0,0.866025,-0.500000,0.394356,0.918958,-0.258819,0.965926,0.587785,0.809017
4,2018-04-02 16:52:00,22215003,BH,Y,(V)STP Base,EMU,375.0,MD,51.180550,0.49318,51.546120,-0.075130,6.0,0.866025,-0.500000,0.394356,0.918958,-0.866025,-0.500000,-0.743145,0.669131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546706,2023-01-14 20:28:00,22215003,SA,Y,LTP,EMU,378.0,OF,51.378426,-0.10256,51.397017,-0.075196,7.0,0.500000,0.866025,0.299363,-0.954139,-0.866025,0.500000,0.207912,-0.978148
546707,2023-01-14 20:41:00,22215003,SA,Y,LTP,EMU,378.0,OF,51.378426,-0.10256,51.397017,-0.075196,5.0,0.500000,0.866025,0.299363,-0.954139,-0.866025,0.500000,-0.913545,-0.406737
546708,2023-02-14 14:59:00,22204000,WD,Y,LTP,EMU,378.0,MQ,51.471070,-0.16936,51.497930,-0.210160,3.0,0.866025,0.500000,0.299363,-0.954139,-0.500000,-0.866025,-0.104528,0.994522
546709,2023-02-14 15:33:00,22214000,WD,Y,LTP,EMU,378.0,MQ,51.532500,-0.24454,51.555480,-0.151360,3.0,0.866025,0.500000,0.299363,-0.954139,-0.707107,-0.707107,-0.309017,-0.951057
546710,2023-02-14 14:09:00,22215003,WD,Y,LTP,EMU,378.0,MQ,51.378426,-0.10256,51.397017,-0.075196,1.0,0.866025,0.500000,0.299363,-0.954139,-0.500000,-0.866025,0.809017,0.587785

In [152]:
trim_df.TRAIN_SERVICE_CODE_AFFECTED.value_counts() # one hot

22214000    111581
22215003     61599
21921000     53821
22218000     52150
22216000     42954
21234001     41158
22216001     35921
22204000     29045
21235001     20018
22206000     17527
25234001     10221
21252001      8048
25235001      4579
21237001       192
22215002        14
Name: TRAIN_SERVICE_CODE_AFFECTED, dtype: int64

In [153]:
trim_df.ENGLISH_DAY_TYPE.value_counts() # ohe

WD    401528
SA     44371
SU     37325
BH      5580
BD        24
Name: ENGLISH_DAY_TYPE, dtype: int64

In [154]:
trim_df.APP_TIMETABLE_FLAG_AFF.value_counts() #ohe if binary drop

Y    483737
N      5091
Name: APP_TIMETABLE_FLAG_AFF, dtype: int64

In [155]:
trim_df.loc[:, 'APP_TIMETABLE_FLAG_AFF'] = trim_df.APP_TIMETABLE_FLAG_AFF.apply(lambda x: 1 if x == 'Y' else 0)

In [156]:
trim_df.TRAIN_SCHEDULE_TYPE_AFFECTED.value_counts() # change to only ltp and vstp

LTP                    425294
(V)STP Overlay          33963
(V)STP Base             29567
(V)STP Cancellation         4
Name: TRAIN_SCHEDULE_TYPE_AFFECTED, dtype: int64

In [157]:
trim_df.loc[:, 'TRAIN_SCHEDULE_TYPE_AFFECTED'] = trim_df.TRAIN_SCHEDULE_TYPE_AFFECTED.apply(lambda x: 0 if 'STP' in x else 1)
trim_df

,EVENT_DATETIME,TRAIN_SERVICE_CODE_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_REASON,Lat_OR,Lon_OR,Lat_DES,Lon_DES,PFPI_MINUTES
0,2018-04-01 11:49:00,21921000,SU,1,1,DMS,NaN,MD,51.580430,-0.07182,51.555480,-0.151360,6.0
1,2018-04-01 11:50:00,21921000,SU,1,1,DMS,NaN,MD,51.555480,-0.15136,51.580430,-0.071820,13.0
2,2018-04-01 11:46:00,21921000,SU,1,1,DMS,NaN,MD,51.555480,-0.15136,51.555480,-0.151360,6.0
3,2018-04-02 23:06:00,22215003,BH,1,0,EMU,375.0,MD,51.180550,0.49318,51.180550,0.493180,9.0
4,2018-04-02 16:52:00,22215003,BH,1,0,EMU,375.0,MD,51.180550,0.49318,51.546120,-0.075130,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
546706,2023-01-14 20:28:00,22215003,SA,1,1,EMU,378.0,OF,51.378426,-0.10256,51.397017,-0.075196,7.0
546707,2023-01-14 20:41:00,22215003,SA,1,1,EMU,378.0,OF,51.378426,-0.10256,51.397017,-0.075196,5.0
546708,2023-02-14 14:59:00,22204000,WD,1,1,EMU,378.0,MQ,51.471070,-0.16936,51.497930,-0.210160,3.0
546709,2023-02-14 15:33:00,22214000,WD,1,1,EMU,378.0,MQ,51.532500,-0.24454,51.555480,-0.151360,3.0
546710,2023-02-14 14:09:00,22215003,WD,1,1,EMU,378.0,MQ,51.378426,-0.10256,51.397017,-0.075196,1.0

In [158]:
trim_df[trim_df.TRACTION_TYPE_AFFECTED.isnull()] # drop?

,EVENT_DATETIME,TRAIN_SERVICE_CODE_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,TRAIN_SCHEDULE_TYPE_AFFECTED,TRACTION_TYPE_AFFECTED,UNIT_CLASS_AFFECTED,INCIDENT_REASON,Lat_OR,Lon_OR,Lat_DES,Lon_DES,PFPI_MINUTES
1717,2018-10-21 23:39:00,22215003,SU,0,0,NaN,NaN,MD,51.546120,-0.075130,51.546120,-0.075130,18.0
2806,2019-02-13 07:32:00,22215003,WD,0,0,NaN,NaN,MD,51.493190,-0.047520,51.493190,-0.047520,4.0
3673,2019-08-21 14:35:00,22216001,WD,1,0,NaN,NaN,MD,51.580430,-0.071820,51.532400,-0.244530,24.0
3885,2019-05-09 10:50:00,21252001,WD,0,0,NaN,NaN,MD,51.550920,0.034800,51.559000,0.068970,10.0
4089,2019-10-28 20:17:00,22216001,WD,0,0,NaN,NaN,MD,51.663533,-0.396494,51.663533,-0.396494,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
546123,2022-12-08 17:03:00,22216001,WD,0,0,NaN,NaN,OR,51.463350,-0.172530,51.463350,-0.172530,16.0
546595,2022-06-14 19:28:00,22216001,WD,0,0,NaN,NaN,JF,51.530940,-0.241300,51.542210,-0.276550,7.0
546596,2022-06-14 19:04:00,22216001,WD,0,0,NaN,NaN,JF,51.497930,-0.210160,51.520890,-0.228470,3.0
546597,2022-06-14 18:58:00,22216001,WD,0,0,NaN,NaN,JF,51.471070,-0.169360,51.497930,-0.210160,4.0
546598,2022-06-14 18:47:00,22216001,WD,0,0,NaN,NaN,JF,51.463350,-0.172530,51.463350,-0.172530,7.0

In [159]:
trim_df = trim_df[~trim_df.TRACTION_TYPE_AFFECTED.isnull()]

In [160]:
trim_df = trim_df[trim_df.TRACTION_TYPE_AFFECTED != 'L']

In [161]:
trim_df.TRACTION_TYPE_AFFECTED.value_counts()

EMU    483179
DMS       451
Name: TRACTION_TYPE_AFFECTED, dtype: int64

In [162]:
trim_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 483630 entries, 0 to 546710
Data columns (total 13 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   EVENT_DATETIME                483630 non-null  datetime64[ns]
 1   TRAIN_SERVICE_CODE_AFFECTED   483630 non-null  int64
 2   ENGLISH_DAY_TYPE              483630 non-null  object
 3   APP_TIMETABLE_FLAG_AFF        483630 non-null  int64
 4   TRAIN_SCHEDULE_TYPE_AFFECTED  483630 non-null  int64
 5   TRACTION_TYPE_AFFECTED        483630 non-null  object
 6   UNIT_CLASS_AFFECTED           482149 non-null  float64
 7   INCIDENT_REASON               483630 non-null  object
 8   Lat_OR                        483630 non-null  float64
 9   Lon_OR                        483630 non-null  float64
 10  Lat_DES                       483630 non-null  float64
 11  Lon_DES                       483630 non-null  float64
 12  PFPI_MINUTES                  483630 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(3), object(3)
memory usage: 51.7+ MB

In [164]:
trim_df[['TRACTION_TYPE_AFFECTED', 'UNIT_CLASS_AFFECTED']]['UNIT_CLASS_AFFECTED'].isnull().sum() # convert to others

1481

In [172]:
trim_df[trim_df.TRACTION_TYPE_AFFECTED != 'DMS']['UNIT_CLASS_AFFECTED'].isnull().sum() # drop?

1030

In [175]:
trim_df.INCIDENT_REASON.apply(lambda x: x[0]).value_counts()

I    97873
T    80481
J    60524
O    55463
M    47831
R    38483
X    28355
Z    21506
V    21203
Q    17575
F     9448
A     4559
D      302
Y       27
Name: INCIDENT_REASON, dtype: int64

In [187]:
trim_df.UNIT_CLASS_AFFECTED.value_counts()

378.0    217288
710.0    119815
375.0     84648
315.0     28230
313.0     20817
317.0     11263
321.0        88
Name: UNIT_CLASS_AFFECTED, dtype: int64

In [199]:
trim_df.UNIT_CLASS_AFFECTED.astype('Int64').astype(str).replace('<NA>', 'others')

0         others
1         others
2         others
3            375
4            375
           ...
546706       378
546707       378
546708       378
546709       378
546710       378
Name: UNIT_CLASS_AFFECTED, Length: 483630, dtype: object