# Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [29]:
from preprocess import *

ModuleNotFoundError: No module named 'preprocess'

In [2]:
df = pd.read_csv('/home/lewis/code/TrainDelays/TrainDelays/data/All Delays 2019-20 P01.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479473 entries, 0 to 479472
Data columns (total 39 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   FINANCIAL_YEAR_AND_PERIOD       479473 non-null  object
 1   ORIGIN_DEPARTURE_DATE           479473 non-null  object
 2   TRUST_TRAIN_ID_AFFECTED         479473 non-null  object
 3   PLANNED_ORIG_LOC_CODE_AFF       479473 non-null  int64
 4   PLANNED_ORIG_GBTT_DATETIME_AFF  344092 non-null  object
 5   PLANNED_ORIG_WTT_DATETIME_AFF   479473 non-null  object
 6   PLANNED_DEST_LOC_CODE_AFFECTED  479473 non-null  int64
 7   PLANNED_DEST_GBTT_DATETIME_AFF  344092 non-null  object
 8   PLANNED_DEST_WTT_DATETIME_AFF   479473 non-null  object
 9   TRAIN_SERVICE_CODE_AFFECTED     479473 non-null  int64
 10  SERVICE_GROUP_CODE_AFFECTED     479473 non-null  object
 11  OPERATOR_AFFECTED               479473 non-null  object
 12  ENGLISH_DAY_TYPE                479473 non-null  object
 13  APP_TIMETABLE_FLAG_AFF          479473 non-null  object
 14  TRAIN_SCHEDULE_TYPE_AFFECTED    479473 non-null  object
 15  TRACTION_TYPE_AFFECTED          475615 non-null  object
 16  TRAILING_LOAD_AFFECTED          50762 non-null   float64
 17  TIMING_LOAD_AFFECTED            121639 non-null  object
 18  UNIT_CLASS_AFFECTED             136121 non-null  float64
 19  INCIDENT_NUMBER                 479473 non-null  int64
 20  INCIDENT_CREATE_DATE            479473 non-null  object
 21  INCIDENT_START_DATETIME         479473 non-null  object
 22  INCIDENT_END_DATETIME           479473 non-null  object
 23  SECTION_CODE                    479473 non-null  object
 24  NETWORK_RAIL_LOCATION_MANAGER   479473 non-null  object
 25  RESPONSIBLE_MANAGER             479473 non-null  object
 26  INCIDENT_REASON                 479178 non-null  object
 27  ATTRIBUTION_STATUS              479473 non-null  object
 28  INCIDENT_EQUIPMENT              223623 non-null  object
 29  INCIDENT_DESCRIPTION            479473 non-null  object
 30  REACTIONARY_REASON_CODE         301769 non-null  object
 31  INCIDENT_RESPONSIBLE_TRAIN      190054 non-null  object
 32  PERFORMANCE_EVENT_CODE          479473 non-null  object
 33  START_STANOX                    479473 non-null  int64
 34  END_STANOX                      479473 non-null  int64
 35  EVENT_DATETIME                  479473 non-null  object
 36  PFPI_MINUTES                    479473 non-null  float64
 37  TRUST_TRAIN_ID_RESP             180503 non-null  object
 38  TRUST_TRAIN_ID_REACT            167675 non-null  object
dtypes: float64(3), int64(6), object(30)
memory usage: 142.7+ MB

In [4]:
df.drop(columns=['TRAILING_LOAD_AFFECTED','TIMING_LOAD_AFFECTED', 'UNIT_CLASS_AFFECTED','INCIDENT_EQUIPMENT','TRUST_TRAIN_ID_REACT','TRUST_TRAIN_ID_RESP'], inplace=True)

In [5]:
df.drop(columns = ['FINANCIAL_YEAR_AND_PERIOD',
                 'PLANNED_DEST_WTT_DATETIME_AFF',
                 'PLANNED_ORIG_GBTT_DATETIME_AFF',
                 'PLANNED_ORIG_WTT_DATETIME_AFF',
                 'PLANNED_DEST_GBTT_DATETIME_AFF',
                 'PLANNED_DEST_WTT_DATETIME_AFF',
                 'TRAIN_SCHEDULE_TYPE_AFFECTED',
                 'TRACTION_TYPE_AFFECTED',
                 'INCIDENT_NUMBER',
                 'INCIDENT_CREATE_DATE', 'INCIDENT_START_DATETIME',
                 'INCIDENT_END_DATETIME', 'SECTION_CODE',
                 'NETWORK_RAIL_LOCATION_MANAGER', 'RESPONSIBLE_MANAGER',
                 'ATTRIBUTION_STATUS',
                 'INCIDENT_DESCRIPTION', 'REACTIONARY_REASON_CODE',
                 'INCIDENT_RESPONSIBLE_TRAIN', 'EVENT_DATETIME'
                ], inplace=True)

In [6]:
df.head(20)

,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,OPERATOR_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,INCIDENT_REASON,PERFORMANCE_EVENT_CODE,START_STANOX,END_STANOX,PFPI_MINUTES
0,01/04/2019 00:00,0043612L01,713,89735,57610311,6103,WA,WD,N,FN,M,713,713,0.0
1,01/04/2019 00:00,0044512301,713,89735,57610311,6103,WA,WD,N,FN,M,713,713,0.0
2,01/04/2019 00:00,009I17MD01,850,63631,81010001,GA01,GA,WD,Y,TN,M,850,89582,6.0
3,01/04/2019 00:00,009I33ML01,850,63631,81010003,GA01,GA,WD,Y,TN,M,850,89582,9.0
4,01/04/2019 00:00,009I63MZ01,850,63631,81010003,GA01,GA,WD,Y,TN,M,850,89582,7.0
5,01/04/2019 00:00,009O13MD01,750,63631,81010001,GA01,GA,WD,Y,TN,M,750,89582,6.0
6,01/04/2019 00:00,009O19MG01,750,63631,81010002,GA01,GA,WD,Y,PB,A,89428,89428,0.0
7,01/04/2019 00:00,009O19MG01,750,63631,81010002,GA01,GA,WD,Y,R2,M,89428,89428,5.0
8,01/04/2019 00:00,009O47MU01,750,63631,81010001,GA01,GA,WD,Y,TN,M,750,89582,30.0
9,01/04/2019 00:00,009O55MY01,750,63631,81010003,GA01,GA,WD,Y,TN,M,750,89582,68.0
10,01/04/2019 00:00,009O57MV01,799,63631,81010004,GA01,GA,WD,Y,TN,M,52213,52217,3.0
11,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,GA,WD,Y,PB,A,89428,89428,0.0
12,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,GA,WD,Y,TN,M,750,89582,13.0
13,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,GA,WD,Y,IA,M,89552,89540,3.0
14,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,GA,WD,Y,IA,M,89554,89552,22.0
15,01/04/2019 00:00,009O61MZ01,750,63631,81010001,GA01,GA,WD,Y,TN,M,750,89582,14.0
16,01/04/2019 00:00,009O61MZ01,750,63631,81010001,GA01,GA,WD,Y,IA,M,89566,89556,38.0
17,01/04/2019 00:00,009O63M701,750,63631,81010003,GA01,GA,WD,Y,IA,M,89566,89556,25.0
18,01/04/2019 00:00,011A44M501,1100,2071,23547003,HA04,HA,WD,Y,ZU,M,2007,2015,3.0
19,01/04/2019 00:00,011A44M501,1100,2071,23547003,HA04,HA,WD,Y,ZU,M,2015,2029,3.0

In [7]:
df.dropna(inplace=True)

In [8]:
df.shape

(479178, 14)

In [9]:
df['OPERATOR_AFFECTED'].unique()

array(['WA', 'GA', 'HA', 'HB', 'ES', 'R2', 'ZZ', 'XH', 'PH', 'RD', 'EH',
       'P4', 'RG', 'D1', 'P1', 'PE', 'EA', 'HF', 'D2', 'DB', 'ED', 'LR',
       'PG', 'EC', 'W1', 'PR', 'X2', 'EM', 'PF', 'RH', 'SJ', 'HL', 'HE',
       'RR', 'EJ', 'ET', 'EB', 'EX', 'HT', 'EK', 'RZ', 'XE', 'PO', 'RT',
       'HO', 'HU', 'EF', 'XC', 'PA', 'HM', 'HY', 'LS', 'PV', 'T1', 'P5',
       'X1', 'TY', 'P8', 'LC', 'P7', 'XX', 'R4'], dtype=object)

In [10]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [11]:
data = df[['ENGLISH_DAY_TYPE', 'PERFORMANCE_EVENT_CODE', 'OPERATOR_AFFECTED']]

In [12]:
ohe = OneHotEncoder(sparse=False).fit(data)

/home/lewis/.pyenv/versions/3.10.6/envs/lewagon1#/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [13]:
df[ohe.get_feature_names_out()] = ohe.transform(data)

In [14]:
df.head()

,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,OPERATOR_AFFECTED,ENGLISH_DAY_TYPE,APP_TIMETABLE_FLAG_AFF,INCIDENT_REASON,...,OPERATOR_AFFECTED_TY,OPERATOR_AFFECTED_W1,OPERATOR_AFFECTED_WA,OPERATOR_AFFECTED_X1,OPERATOR_AFFECTED_X2,OPERATOR_AFFECTED_XC,OPERATOR_AFFECTED_XE,OPERATOR_AFFECTED_XH,OPERATOR_AFFECTED_XX,OPERATOR_AFFECTED_ZZ
0,01/04/2019 00:00,0043612L01,713,89735,57610311,6103,WA,WD,N,FN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,01/04/2019 00:00,0044512301,713,89735,57610311,6103,WA,WD,N,FN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,01/04/2019 00:00,009I17MD01,850,63631,81010001,GA01,GA,WD,Y,TN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,01/04/2019 00:00,009I33ML01,850,63631,81010003,GA01,GA,WD,Y,TN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,01/04/2019 00:00,009I63MZ01,850,63631,81010003,GA01,GA,WD,Y,TN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
df.drop(columns=['ENGLISH_DAY_TYPE', 'PERFORMANCE_EVENT_CODE', 'OPERATOR_AFFECTED'], inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 479178 entries, 0 to 479472
Data columns (total 85 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ORIGIN_DEPARTURE_DATE           479178 non-null  object
 1   TRUST_TRAIN_ID_AFFECTED         479178 non-null  object
 2   PLANNED_ORIG_LOC_CODE_AFF       479178 non-null  int64
 3   PLANNED_DEST_LOC_CODE_AFFECTED  479178 non-null  int64
 4   TRAIN_SERVICE_CODE_AFFECTED     479178 non-null  int64
 5   SERVICE_GROUP_CODE_AFFECTED     479178 non-null  object
 6   APP_TIMETABLE_FLAG_AFF          479178 non-null  object
 7   INCIDENT_REASON                 479178 non-null  object
 8   START_STANOX                    479178 non-null  int64
 9   END_STANOX                      479178 non-null  int64
 10  PFPI_MINUTES                    479178 non-null  float64
 11  ENGLISH_DAY_TYPE_BH             479178 non-null  float64
 12  ENGLISH_DAY_TYPE_SA             479178 non-null  float64
 13  ENGLISH_DAY_TYPE_SU             479178 non-null  float64
 14  ENGLISH_DAY_TYPE_WD             479178 non-null  float64
 15  PERFORMANCE_EVENT_CODE_A        479178 non-null  float64
 16  PERFORMANCE_EVENT_CODE_C        479178 non-null  float64
 17  PERFORMANCE_EVENT_CODE_D        479178 non-null  float64
 18  PERFORMANCE_EVENT_CODE_F        479178 non-null  float64
 19  PERFORMANCE_EVENT_CODE_M        479178 non-null  float64
 20  PERFORMANCE_EVENT_CODE_O        479178 non-null  float64
 21  PERFORMANCE_EVENT_CODE_P        479178 non-null  float64
 22  PERFORMANCE_EVENT_CODE_S        479178 non-null  float64
 23  OPERATOR_AFFECTED_D1            479178 non-null  float64
 24  OPERATOR_AFFECTED_D2            479178 non-null  float64
 25  OPERATOR_AFFECTED_DB            479178 non-null  float64
 26  OPERATOR_AFFECTED_EA            479178 non-null  float64
 27  OPERATOR_AFFECTED_EB            479178 non-null  float64
 28  OPERATOR_AFFECTED_EC            479178 non-null  float64
 29  OPERATOR_AFFECTED_ED            479178 non-null  float64
 30  OPERATOR_AFFECTED_EF            479178 non-null  float64
 31  OPERATOR_AFFECTED_EH            479178 non-null  float64
 32  OPERATOR_AFFECTED_EJ            479178 non-null  float64
 33  OPERATOR_AFFECTED_EK            479178 non-null  float64
 34  OPERATOR_AFFECTED_EM            479178 non-null  float64
 35  OPERATOR_AFFECTED_ES            479178 non-null  float64
 36  OPERATOR_AFFECTED_ET            479178 non-null  float64
 37  OPERATOR_AFFECTED_EX            479178 non-null  float64
 38  OPERATOR_AFFECTED_GA            479178 non-null  float64
 39  OPERATOR_AFFECTED_HA            479178 non-null  float64
 40  OPERATOR_AFFECTED_HB            479178 non-null  float64
 41  OPERATOR_AFFECTED_HE            479178 non-null  float64
 42  OPERATOR_AFFECTED_HF            479178 non-null  float64
 43  OPERATOR_AFFECTED_HL            479178 non-null  float64
 44  OPERATOR_AFFECTED_HM            479178 non-null  float64
 45  OPERATOR_AFFECTED_HO            479178 non-null  float64
 46  OPERATOR_AFFECTED_HT            479178 non-null  float64
 47  OPERATOR_AFFECTED_HU            479178 non-null  float64
 48  OPERATOR_AFFECTED_HY            479178 non-null  float64
 49  OPERATOR_AFFECTED_LC            479178 non-null  float64
 50  OPERATOR_AFFECTED_LR            479178 non-null  float64
 51  OPERATOR_AFFECTED_LS            479178 non-null  float64
 52  OPERATOR_AFFECTED_P1            479178 non-null  float64
 53  OPERATOR_AFFECTED_P4            479178 non-null  float64
 54  OPERATOR_AFFECTED_P5            479178 non-null  float64
 55  OPERATOR_AFFECTED_P7            479178 non-null  float64
 56  OPERATOR_AFFECTED_P8            479178 non-null  float64
 57  OPERATOR_AFFECTED_PA            479178 non-null  float64
 58  OPERATOR_AFFECTED_PE            479178 non-null  float64
 59  OPERATOR_AFFECTED_PF            479178 non-null  float64
 60  OPERATOR_AFFECTED_PG            479178 non-null  float64
 61  OPERATOR_AFFECTED_PH            479178 non-null  float64
 62  OPERATOR_AFFECTED_PO            479178 non-null  float64
 63  OPERATOR_AFFECTED_PR            479178 non-null  float64
 64  OPERATOR_AFFECTED_PV            479178 non-null  float64
 65  OPERATOR_AFFECTED_R2            479178 non-null  float64
 66  OPERATOR_AFFECTED_R4            479178 non-null  float64
 67  OPERATOR_AFFECTED_RD            479178 non-null  float64
 68  OPERATOR_AFFECTED_RG            479178 non-null  float64
 69  OPERATOR_AFFECTED_RH            479178 non-null  float64
 70  OPERATOR_AFFECTED_RR            479178 non-null  float64
 71  OPERATOR_AFFECTED_RT            479178 non-null  float64
 72  OPERATOR_AFFECTED_RZ            479178 non-null  float64
 73  OPERATOR_AFFECTED_SJ            479178 non-null  float64
 74  OPERATOR_AFFECTED_T1            479178 non-null  float64
 75  OPERATOR_AFFECTED_TY            479178 non-null  float64
 76  OPERATOR_AFFECTED_W1            479178 non-null  float64
 77  OPERATOR_AFFECTED_WA            479178 non-null  float64
 78  OPERATOR_AFFECTED_X1            479178 non-null  float64
 79  OPERATOR_AFFECTED_X2            479178 non-null  float64
 80  OPERATOR_AFFECTED_XC            479178 non-null  float64
 81  OPERATOR_AFFECTED_XE            479178 non-null  float64
 82  OPERATOR_AFFECTED_XH            479178 non-null  float64
 83  OPERATOR_AFFECTED_XX            479178 non-null  float64
 84  OPERATOR_AFFECTED_ZZ            479178 non-null  float64
dtypes: float64(75), int64(5), object(5)
memory usage: 314.4+ MB

In [17]:
df.drop(columns=['OPERATOR_AFFECTED_ZZ'], inplace=True)

In [18]:
df['CANCELLATIONS'] = df['PERFORMANCE_EVENT_CODE_A'] = df['PERFORMANCE_EVENT_CODE_M']

In [19]:
df['DELAYS'] = df['PERFORMANCE_EVENT_CODE_C'] + df['PERFORMANCE_EVENT_CODE_D'] + df['PERFORMANCE_EVENT_CODE_O'] + df['PERFORMANCE_EVENT_CODE_P'] + df['PERFORMANCE_EVENT_CODE_S'] + df['PERFORMANCE_EVENT_CODE_F']

In [20]:
df.drop(columns=['PERFORMANCE_EVENT_CODE_A', 'PERFORMANCE_EVENT_CODE_C',
       'PERFORMANCE_EVENT_CODE_D', 'PERFORMANCE_EVENT_CODE_F',
       'PERFORMANCE_EVENT_CODE_M', 'PERFORMANCE_EVENT_CODE_O',
       'PERFORMANCE_EVENT_CODE_P', 'PERFORMANCE_EVENT_CODE_S'], inplace=True)

In [21]:
df.shape

(479178, 78)

In [22]:
df.head(15)

,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,TRAIN_SERVICE_CODE_AFFECTED,SERVICE_GROUP_CODE_AFFECTED,APP_TIMETABLE_FLAG_AFF,INCIDENT_REASON,START_STANOX,END_STANOX,...,OPERATOR_AFFECTED_W1,OPERATOR_AFFECTED_WA,OPERATOR_AFFECTED_X1,OPERATOR_AFFECTED_X2,OPERATOR_AFFECTED_XC,OPERATOR_AFFECTED_XE,OPERATOR_AFFECTED_XH,OPERATOR_AFFECTED_XX,CANCELLATIONS,DELAYS
0,01/04/2019 00:00,0043612L01,713,89735,57610311,6103,N,FN,713,713,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,01/04/2019 00:00,0044512301,713,89735,57610311,6103,N,FN,713,713,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,01/04/2019 00:00,009I17MD01,850,63631,81010001,GA01,Y,TN,850,89582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,01/04/2019 00:00,009I33ML01,850,63631,81010003,GA01,Y,TN,850,89582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,01/04/2019 00:00,009I63MZ01,850,63631,81010003,GA01,Y,TN,850,89582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,01/04/2019 00:00,009O13MD01,750,63631,81010001,GA01,Y,TN,750,89582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,01/04/2019 00:00,009O19MG01,750,63631,81010002,GA01,Y,PB,89428,89428,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,01/04/2019 00:00,009O19MG01,750,63631,81010002,GA01,Y,R2,89428,89428,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8,01/04/2019 00:00,009O47MU01,750,63631,81010001,GA01,Y,TN,750,89582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,01/04/2019 00:00,009O55MY01,750,63631,81010003,GA01,Y,TN,750,89582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,01/04/2019 00:00,009O57MV01,799,63631,81010004,GA01,Y,TN,52213,52217,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,Y,PB,89428,89428,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,Y,TN,750,89582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,Y,IA,89552,89540,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14,01/04/2019 00:00,009O59MZ01,750,63631,81010002,GA01,Y,IA,89554,89552,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [23]:
df['DELAYS'].value_counts()

0.0    331042
1.0    148136
Name: DELAYS, dtype: int64

In [24]:
df.shape

(479178, 78)

In [25]:
df.columns

Index(['ORIGIN_DEPARTURE_DATE', 'TRUST_TRAIN_ID_AFFECTED',
       'PLANNED_ORIG_LOC_CODE_AFF', 'PLANNED_DEST_LOC_CODE_AFFECTED',
       'TRAIN_SERVICE_CODE_AFFECTED', 'SERVICE_GROUP_CODE_AFFECTED',
       'APP_TIMETABLE_FLAG_AFF', 'INCIDENT_REASON', 'START_STANOX',
       'END_STANOX', 'PFPI_MINUTES', 'ENGLISH_DAY_TYPE_BH',
       'ENGLISH_DAY_TYPE_SA', 'ENGLISH_DAY_TYPE_SU', 'ENGLISH_DAY_TYPE_WD',
       'OPERATOR_AFFECTED_D1', 'OPERATOR_AFFECTED_D2', 'OPERATOR_AFFECTED_DB',
       'OPERATOR_AFFECTED_EA', 'OPERATOR_AFFECTED_EB', 'OPERATOR_AFFECTED_EC',
       'OPERATOR_AFFECTED_ED', 'OPERATOR_AFFECTED_EF', 'OPERATOR_AFFECTED_EH',
       'OPERATOR_AFFECTED_EJ', 'OPERATOR_AFFECTED_EK', 'OPERATOR_AFFECTED_EM',
       'OPERATOR_AFFECTED_ES', 'OPERATOR_AFFECTED_ET', 'OPERATOR_AFFECTED_EX',
       'OPERATOR_AFFECTED_GA', 'OPERATOR_AFFECTED_HA', 'OPERATOR_AFFECTED_HB',
       'OPERATOR_AFFECTED_HE', 'OPERATOR_AFFECTED_HF', 'OPERATOR_AFFECTED_HL',
       'OPERATOR_AFFECTED_HM', 'OPERATOR_AFFECTED_HO', 'OPERATOR_AFFECTED_HT',
       'OPERATOR_AFFECTED_HU', 'OPERATOR_AFFECTED_HY', 'OPERATOR_AFFECTED_LC',
       'OPERATOR_AFFECTED_LR', 'OPERATOR_AFFECTED_LS', 'OPERATOR_AFFECTED_P1',
       'OPERATOR_AFFECTED_P4', 'OPERATOR_AFFECTED_P5', 'OPERATOR_AFFECTED_P7',
       'OPERATOR_AFFECTED_P8', 'OPERATOR_AFFECTED_PA', 'OPERATOR_AFFECTED_PE',
       'OPERATOR_AFFECTED_PF', 'OPERATOR_AFFECTED_PG', 'OPERATOR_AFFECTED_PH',
       'OPERATOR_AFFECTED_PO', 'OPERATOR_AFFECTED_PR', 'OPERATOR_AFFECTED_PV',
       'OPERATOR_AFFECTED_R2', 'OPERATOR_AFFECTED_R4', 'OPERATOR_AFFECTED_RD',
       'OPERATOR_AFFECTED_RG', 'OPERATOR_AFFECTED_RH', 'OPERATOR_AFFECTED_RR',
       'OPERATOR_AFFECTED_RT', 'OPERATOR_AFFECTED_RZ', 'OPERATOR_AFFECTED_SJ',
       'OPERATOR_AFFECTED_T1', 'OPERATOR_AFFECTED_TY', 'OPERATOR_AFFECTED_W1',
       'OPERATOR_AFFECTED_WA', 'OPERATOR_AFFECTED_X1', 'OPERATOR_AFFECTED_X2',
       'OPERATOR_AFFECTED_XC', 'OPERATOR_AFFECTED_XE', 'OPERATOR_AFFECTED_XH',
       'OPERATOR_AFFECTED_XX', 'CANCELLATIONS', 'DELAYS'],
      dtype='object')

In [ ]:
mine = ['ORIGIN_DEPARTURE_DATE', 'TRUST_TRAIN_ID_AFFECTED',
       'PLANNED_ORIG_LOC_CODE_AFF', 'PLANNED_DEST_LOC_CODE_AFFECTED',
       'TRAIN_SERVICE_CODE_AFFECTED', 'SERVICE_GROUP_CODE_AFFECTED',
       'APP_TIMETABLE_FLAG_AFF', 'INCIDENT_REASON', 'START_STANOX',
       'END_STANOX', 'PFPI_MINUTES', 'ENGLISH_DAY_TYPE_BH',
       'ENGLISH_DAY_TYPE_SA', 'ENGLISH_DAY_TYPE_SU', 'ENGLISH_DAY_TYPE_WD',
       'OPERATOR_AFFECTED_D1', 'OPERATOR_AFFECTED_D2', 'OPERATOR_AFFECTED_DB',
       'OPERATOR_AFFECTED_EA', 'OPERATOR_AFFECTED_EB', 'OPERATOR_AFFECTED_EC',
       'OPERATOR_AFFECTED_ED', 'OPERATOR_AFFECTED_EF', 'OPERATOR_AFFECTED_EH',
       'OPERATOR_AFFECTED_EJ', 'OPERATOR_AFFECTED_EK', 'OPERATOR_AFFECTED_EM',
       'OPERATOR_AFFECTED_ES', 'OPERATOR_AFFECTED_ET', 'OPERATOR_AFFECTED_EX',
       'OPERATOR_AFFECTED_GA', 'OPERATOR_AFFECTED_HA', 'OPERATOR_AFFECTED_HB',
       'OPERATOR_AFFECTED_HE', 'OPERATOR_AFFECTED_HF', 'OPERATOR_AFFECTED_HL',
       'OPERATOR_AFFECTED_HM', 'OPERATOR_AFFECTED_HO', 'OPERATOR_AFFECTED_HT',
       'OPERATOR_AFFECTED_HU', 'OPERATOR_AFFECTED_HY', 'OPERATOR_AFFECTED_LC',
       'OPERATOR_AFFECTED_LR', 'OPERATOR_AFFECTED_LS', 'OPERATOR_AFFECTED_P1',
       'OPERATOR_AFFECTED_P4', 'OPERATOR_AFFECTED_P5', 'OPERATOR_AFFECTED_P7',
       'OPERATOR_AFFECTED_P8', 'OPERATOR_AFFECTED_PA', 'OPERATOR_AFFECTED_PE',
       'OPERATOR_AFFECTED_PF', 'OPERATOR_AFFECTED_PG', 'OPERATOR_AFFECTED_PH',
       'OPERATOR_AFFECTED_PO', 'OPERATOR_AFFECTED_PR', 'OPERATOR_AFFECTED_PV',
       'OPERATOR_AFFECTED_R2', 'OPERATOR_AFFECTED_R4', 'OPERATOR_AFFECTED_RD',
       'OPERATOR_AFFECTED_RG', 'OPERATOR_AFFECTED_RH', 'OPERATOR_AFFECTED_RR',
       'OPERATOR_AFFECTED_RT', 'OPERATOR_AFFECTED_RZ', 'OPERATOR_AFFECTED_SJ',
       'OPERATOR_AFFECTED_T1', 'OPERATOR_AFFECTED_TY', 'OPERATOR_AFFECTED_W1',
       'OPERATOR_AFFECTED_WA', 'OPERATOR_AFFECTED_X1', 'OPERATOR_AFFECTED_X2',
       'OPERATOR_AFFECTED_XC', 'OPERATOR_AFFECTED_XE', 'OPERATOR_AFFECTED_XH',
       'OPERATOR_AFFECTED_XX', 'CANCELLATIONS', 'DELAYS']

bens = ['ORIGIN_DEPARTURE_DATE', 'TRUST_TRAIN_ID_AFFECTED',
       'PLANNED_ORIG_LOC_CODE_AFF', 'PLANNED_DEST_LOC_CODE_AFFECTED',
       'TRAIN_SERVICE_CODE_AFFECTED', 'SERVICE_GROUP_CODE_AFFECTED',
       'APP_TIMETABLE_FLAG_AFF', 'INCIDENT_REASON', 'START_STANOX',
       'END_STANOX', 'PFPI_MINUTES', 'ENGLISH_DAY_TYPE_BH',
       'ENGLISH_DAY_TYPE_SA', 'ENGLISH_DAY_TYPE_SU', 'ENGLISH_DAY_TYPE_WD',
       'OPERATOR_AFFECTED_D1', 'OPERATOR_AFFECTED_D2', 'OPERATOR_AFFECTED_DB',
       'OPERATOR_AFFECTED_E1', 'OPERATOR_AFFECTED_EA', 'OPERATOR_AFFECTED_EB',
       'OPERATOR_AFFECTED_EC', 'OPERATOR_AFFECTED_ED', 'OPERATOR_AFFECTED_EF',
       'OPERATOR_AFFECTED_EH', 'OPERATOR_AFFECTED_EJ', 'OPERATOR_AFFECTED_EK',
       'OPERATOR_AFFECTED_EM', 'OPERATOR_AFFECTED_ES', 'OPERATOR_AFFECTED_ET',
       'OPERATOR_AFFECTED_EX', 'OPERATOR_AFFECTED_GA', 'OPERATOR_AFFECTED_HA',
       'OPERATOR_AFFECTED_HB', 'OPERATOR_AFFECTED_HE', 'OPERATOR_AFFECTED_HF',
       'OPERATOR_AFFECTED_HL', 'OPERATOR_AFFECTED_HM', 'OPERATOR_AFFECTED_HO',
       'OPERATOR_AFFECTED_HT', 'OPERATOR_AFFECTED_HU', 'OPERATOR_AFFECTED_HY',
       'OPERATOR_AFFECTED_LR', 'OPERATOR_AFFECTED_LS', 'OPERATOR_AFFECTED_P1',
       'OPERATOR_AFFECTED_P4', 'OPERATOR_AFFECTED_P5', 'OPERATOR_AFFECTED_P7',
       'OPERATOR_AFFECTED_PA', 'OPERATOR_AFFECTED_PE', 'OPERATOR_AFFECTED_PF',
       'OPERATOR_AFFECTED_PG', 'OPERATOR_AFFECTED_PH', 'OPERATOR_AFFECTED_PO',
       'OPERATOR_AFFECTED_PR', 'OPERATOR_AFFECTED_PV', 'OPERATOR_AFFECTED_R2',
       'OPERATOR_AFFECTED_R4', 'OPERATOR_AFFECTED_RD', 'OPERATOR_AFFECTED_RE',
       'OPERATOR_AFFECTED_RG', 'OPERATOR_AFFECTED_RH', 'OPERATOR_AFFECTED_RR',
       'OPERATOR_AFFECTED_RT', 'OPERATOR_AFFECTED_RZ', 'OPERATOR_AFFECTED_W1',
       'OPERATOR_AFFECTED_WA', 'OPERATOR_AFFECTED_X1', 'OPERATOR_AFFECTED_X2',
       'OPERATOR_AFFECTED_XC', 'OPERATOR_AFFECTED_XE', 'OPERATOR_AFFECTED_XH',
       'CANCELATIONS', 'DELAYS']

In [ ]:
unique_op_codes = ['AM', 'AN', 'AR', 'AW', 'ATW', 'CA', 'CC', 'CH', 'CS', 'CT', 'CX',
       'DC', 'EC', 'EM', 'EP', 'ES', 'EU', 'FC', 'GC', 'GE', 'GL', 'GM',
       'GN', 'GR', 'GW', 'GWR', 'GX', 'HB', 'HC', 'HT', 'HX', 'IL', 'LD',
       'LE', 'LF', 'LG', 'LM', 'LN', 'LO', 'LR', 'LS', 'LT', 'ME', 'ML',
       'MV', 'NL', 'NR', 'NS', 'NT', 'NW', 'NY', 'QC', 'RE', 'RT', 'SC',
       'SE', 'SJ', 'SN', 'SO', 'SP', 'SR', 'SS', 'SW', 'SX', 'TL', 'TP',
       'TS', 'TT', 'TW', 'VL', 'VT', 'WB', 'WC', 'WE', 'WM', 'WN', 'WR',
       'WS', 'WW', 'XC', 'XM', 'XP', 'XR', 'XS', 'XX', 'YG']

for code in unique_op_codes:
    if f'OPERATOR_AFFECTED_{code}' not in df.columns:
        df[f'OPERATOR_AFFECTED_{code}'] = 0

In [ ]:
df.shape

In [ ]:
len(unique_op_codes)